# Generated by Django 6.0.5 on 2026-07-04 02:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('AGUA', 'Fuga de agua / alcantarillado'), ('VIAL', 'Bache / Deterioro vial'), ('LUZ', 'Luminaria defectuosa'), ('OTRO', 'Otros daños de Infraestructura')], max_length=4)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='evidencias/')),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('PROG', 'En progreso'), ('RESU', 'Resuelto')], default='PEND', max_length=4)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
