# Generated by Django 6.0.5 on 2026-07-04 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='estado',
        ),
    ]
