# Generated by Django 6.0.5 on 2026-08-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_remove_incidencia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(default='Recibido', max_length=20),
        ),
    ]
